.\" Manpage for Eruption.
.TH man 8 "Nov 2020" "0.0.2" "eruptionctl man page"
.SH NAME
 eruptionctl - A CLI control utility for the Eruption Linux user-mode driver
.SH SYNOPSIS

 USAGE:
    eruptionctl [FLAGS] <SUBCOMMAND>

 FLAGS:
    -h, --help       Prints help information
    -v, --verbose    Verbose mode (-v, -vv, -vvv, etc.)
    -V, --version    Prints version information

 SUBCOMMANDS:
    config      Configuration related sub-commands
    help        Prints this message or the help of the given sub-command(s)
    profiles    Profile related sub-commands
    scripts     Script related sub-commands
    switch      Switch to a different profile or slot

.SH SEE ALSO
 eruption(8), eruption.conf(5), eruption-netfx(1)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
