.\" Manpage for Eruption.
.TH man 8 "Nov 2021" "0.0.1" "eruption-cmd man page"
.SH NAME
 eruption-cmd - A CLI utility for the Eruption Linux user-mode driver SDK
.SH SYNOPSIS

 USAGE:
    eruption-cmd [OPTIONS] <SUBCOMMAND>

 OPTIONS:
    -h, --help       Print help information
    -v, --verbose    Verbose mode (-v, -vv, -vvv, etc.)
    -V, --version    Print version information

 SUBCOMMANDS:
    completions    Generate shell completions
    help           Print this message or the help of the given subcommand(s)

 .SH SEE ALSO
 eruption(8), eruption.conf(5)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
