.\" Manpage for Eruption.
.TH man 8 "Oct 2022" "0.0.14" "eruption-hwutil man page"
.SH NAME
 eruption-hwutil - A CLI control utility for hardware supported by the Eruption Linux user-mode driver
.SH SYNOPSIS

Usage: eruption-hwutil [OPTIONS] <COMMAND>

Commands:
  list         List available devices, use this first to find out the index of the device to address
  status       Query device specific status like e.g.: Signal Strength/Battery Level
  blackout     Turn off all LEDs, but otherwise leave the device completely usable
  firmware     Firmware related subcommands (DANGEROUS, may brick the device)
  completions  Generate shell completions
  help         Print this message or the help of the given subcommand(s)

Options:
  -v, --verbose...       Verbose mode (-v, -vv, -vvv, etc.)
  -r, --repeat           Repeat output until ctrl+c is pressed
  -c, --config <CONFIG>  Sets the configuration file to use
  -h, --help             Print help information
  -V, --version          Print version information


.SH SEE ALSO
 eruption.conf(5), eruptionctl(1), eruption-netfx(1)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
