.\" Manpage for Eruption.
.TH man 1 "Oct 2022" "0.0.25" "eruptionctl man page"
.SH NAME
  eruptionctl - A CLI control utility for the Eruption Linux user-mode driver

.SH SYNOPSIS
.BR

  Usage: eruptionctl [OPTIONS] <COMMAND>

.SH DESCRIPTION
.BR

  Commands:
    config         Configuration related sub-commands
    color-schemes  Define, import or delete a named color scheme
    devices        Get or set some device specific configuration parameters
    status         Shows the currently active profile or slot
    switch         Switch to a different profile or slot
    profiles       Profile related sub-commands
    names          Naming related commands such as renaming of profile slots
    scripts        Script related sub-commands
    param          Get or set script parameters on the currently active profile
    completions    Generate shell completions
    help           Print this message or the help of the given subcommand(s)

  Options:
    -v, --verbose...       Verbose mode (-v, -vv, -vvv, etc.)
    -r, --repeat           Repeat output until ctrl+c is pressed
    -c, --config <CONFIG>  Sets the configuration file to use
    -h, --help             Print help information
    -V, --version          Print version information

.SH EXAMPLES
.BR

  eruptionctl profiles list

  eruptionctl switch profile swirl-perlin-rainbow.profile
  eruptionctl switch profile /var/lib/eruption/profiles/swirl-perlin-rainbow.profile

  eruptionctl switch slot 4

  eruptionctl scripts list

  eruptionctl switch profile matrix.profile
  eruptionctl param "Solid Color" color_background "#ffff0000"

.SH SEE ALSO
  eruption(8), eruption.conf(5), eruption-keymap(1), eruption-macro(1), eruption-netfx(1)
.SH BUGS
  No known bugs
.SH AUTHOR
  X3n0m0rph59 <x3n0m0rph59@gmail.com>
