.\" Manpage for Eruption.
.TH man 5 "May 2020" "0.1.10" "eruption.conf man page"
.SH NAME
 Eruption - Linux user-mode driver for the ROCCAT Vulcan 100/12x series keyboards
.SH SYNOPSIS
.SH DESCRIPTION
# Eruption - Linux user-mode driver for the ROCCAT Vulcan 100/12x series keyboards
.br
# Main configuration file
.br
.br
[global]
.br
profile_dir = "/var/lib/eruption/profiles/"
.br
script_dir = "/usr/share/eruption/scripts/"
.br
.br

# select your keyboard variant
.br
# keyboard_variant = "ANSI"
.br
keyboard_variant = "ISO"
.br
.br

[frontend]
.br
# enabled = true
.br
# theme = "eruption"
.br

.SH Section [global]
.br
keyboard_variant = Switch between sub-variants of your device. (Only partially supported)
.br

.SH Section [frontend]

Please note that the "frontend" (a browser-based GUI) is not currently shipped
with the pre-built packages, since it is considered not ready yet.

.SH SEE ALSO
 eruption(8)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
