.\" Manpage for Eruption.
.TH man 1 "Feb 2022" "0.0.12" "eruption-process-monitor man page"
.SH NAME
 eruption-process-monitor - A daemon to monitor and introspect system processes and events
.SH SYNOPSIS

 USAGE:
    eruption-process-monitor [OPTIONS] [ARGS] <SUBCOMMAND>

 OPTIONS:
    -c, --config <CONFIG>    Sets the configuration file to use
    -h, --help               Print help information
    -v, --verbose            Verbose mode (-v, -vv, -vvv, etc.)
    -V, --version            Print version information

 SUBCOMMANDS:
    completions    Generate shell completions
    daemon         Run in background and monitor running processes
    help           Print this message or the help of the given subcommand(s)
    rules          Rules related sub-commands


.SH SEE ALSO
 eruption(8), eruption.conf(5), eruption-netfx(1)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
