.\" Manpage for Eruption.
.TH man 8 "May 2020" "0.1.10" "eruption man page"
.SH NAME
 Eruption - Linux user-mode driver for the ROCCAT Vulcan 100/12x series keyboards
.SH SYNOPSIS
 eruption [OPTIONS]

.SH FLAGS
    -h, --help       Prints help information
    -V, --version    Prints version information

.SH OPTIONS
    -c, --config <FILE>    Sets the configuration file to use

.SH SEE ALSO
 eruption.conf(5)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
