.\" Manpage for Eruption.
.TH man 8 "Nov 2020" "0.1.19" "eruption man page"
.SH NAME
 Eruption - Linux user-mode input and LED driver for keyboards, mice and other devices
.SH SYNOPSIS
 eruption [OPTIONS]

.SH FLAGS
    -h, --help       Prints help information
    -V, --version    Prints version information

.SH OPTIONS
    -c, --config <FILE>    Sets the configuration file to use

.SH SEE ALSO
 eruption.conf(5), eruptionctl(1), eruption-netfx(1)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
