.\" Manpage for Eruption.
.TH man 5 "Nov 2020" "0.1.19" "eruption.conf man page"
.SH NAME
 Eruption - Linux user-mode input and LED driver for keyboards, mice and other devices
.SH SYNOPSIS
.SH DESCRIPTION
# Eruption - Linux user-mode input and LED driver for keyboards, mice and other devices
.br
.br

# Main configuration file
.br
.br
[global]
.br
profile_dir = "/var/lib/eruption/profiles/"
.br
script_dir = "/usr/share/eruption/scripts/"
.br
.br

.br
# keyboard_variant = "ANSI"
.br
keyboard_variant = "ISO"
.br
.br

enable_mouse = true
.br
grab_mouse = true
.br
.br

afk_profile = "rainbow-wave.profile"
.br
afk_timeout_secs = 0
.br
.br

.SH Section [global]
.br
keyboard_variant = Switch between sub-variants of your device. (Only partially supported)
.br

enable_mouse = Enable support for mouse events. Will open the evdev device in shared mode.
.br
grab_mouse = Enable support for mouse event injection. Will open the evdev device in exclusive mode.
             Disable this feature if you want to use 3rd party mouse driver software.
.br
.br

afk_profile = The profile to load when the user is AFK (Away from Keyboard)
.br
afk_timeout_secs = Time that has to pass without any input events, until AFK mode is activated.
                   Specify 0 seconds to disable the AFK mode feature.
.br

.SH SEE ALSO
 eruption(8), eruptionctl(1), eruption-netfx(1)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
