.\" Manpage for Eruption.
.TH man 8 "Oct 2023" "0.0.7" "eruption-cmd man page"
.SH NAME
  eruption-cmd - A CLI utility for the Eruption Linux user-mode driver SDK
.SH SYNOPSIS
.BR

  Usage: eruption-cmd [OPTIONS] <COMMAND>

.SH DESCRIPTION
.BR

  Options:
    -v, --verbose...  Verbose mode (-v, -vv, -vvv, etc.)
    -h, --help        Print help information
    -V, --version     Print version information


.SH SEE ALSO
  eruption(8), eruption.conf(5)
.SH BUGS
  No known bugs
.SH AUTHOR
  X3n0m0rph59 <x3n0m0rph59@gmail.com>
