.\" Manpage for Eruption.
.TH man 5 "29. November 2019" "0.0.9" "eruption.conf man page"
.SH NAME
 Eruption - Linux user-mode driver for the ROCCAT Vulcan 100/12x series keyboards
.SH SYNOPSIS
.SH DESCRIPTION
 Sections:
    global
    audio_plugin
.SH SEE ALSO
 eruption(8)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
