.\" Manpage for Eruption.
.TH man 1 "Nov 2020" "0.0.1" "eruption-process-monitor man page"
.SH NAME
 eruption-process-monitor - A daemon to monitor and introspect system processes and events
.SH SYNOPSIS

 USAGE:
     eruption-process-monitor [FLAGS] [OPTIONS] [ARGS] <SUBCOMMAND>

 ARGS:
     <hostname>
     <port>

 FLAGS:
     -h, --help       Prints help information
     -v, --verbose    Verbose mode (-v, -vv, -vvv, etc.)
     -V, --version    Prints version information

 OPTIONS:
     -c, --config <config>    Sets the configuration file to use

 SUBCOMMANDS:
     daemon    Run in background and monitor running processes
     help      Prints this message or the help of the given sub-command(s)
     rules     Rules related sub-commands

.SH SEE ALSO
 eruption(8), eruption.conf(5), eruption-netfx(1)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
