.\" Manpage for Eruption.
.TH man 1 "Aug 2021" "0.0.9" "eruptionctl man page"
.SH NAME
 eruptionctl - A CLI control utility for the Eruption Linux user-mode driver
.SH SYNOPSIS

 USAGE:
    eruptionctl [FLAGS] <SUBCOMMAND>

 FLAGS:
    -h, --help       Prints help information
    -v, --verbose    Verbose mode (-v, -vv, -vvv, etc.)
    -V, --version    Prints version information

 SUBCOMMANDS:
    completions    Generate shell completions
    config         Configuration related sub-commands
    devices        Set or query device specific configuration parameters
    help           Prints this message or the help of the given subcommand(s)
    names          Naming related commands such as renaming of profile slots
    param          Get or set script parameters on the currently active profile
    profiles       Profile related sub-commands
    scripts        Script related sub-commands
    status         Shows the currently active profile or slot
    switch         Switch to a different profile or slot

.SH SEE ALSO
 eruption(8), eruption.conf(5), eruption-netfx(1)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
