.\" Manpage for Eruption.
.TH man 1 "Dec 2020" "0.0.2" "eruption-netfx man page"
.SH NAME
 eruption-netfx - A Network FX protocol client for the Eruption Linux user-mode driver
.SH SYNOPSIS

 USAGE:
    eruption-netfx [FLAGS] [ARGS] <SUBCOMMAND>

 ARGS:
    <hostname>
    <port>

 FLAGS:
    -h, --help       Prints help information
    -v, --verbose    Verbose mode (-v, -vv, -vvv, etc.)
    -V, --version    Prints version information

 SUBCOMMANDS:
    ambient    Make the LEDs of connected devices reflect what is shown on the screen
    animation  Load image files from a directory and display each one on the connected devices
    command    Send Network FX protocol commands to the server
    help       Prints this message or the help of the given sub-command(s)
    image      Load an image file and display it on the connected devices
    ping       Pings the server

.SH SEE ALSO
 eruption(8), eruption.conf(5)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
