.\" Manpage for Eruption.
.TH man 8 "Feb 2022" "0.1.23" "eruption man page"
.SH NAME
 Eruption - Realtime RGB LED Driver for Linux
.SH SYNOPSIS
 eruption [OPTIONS]

.SH OPTIONS
    -c, --config <FILE>    Sets the configuration file to use
    -h, --help             Prints help information
    -V, --version          Prints version information


.SH SEE ALSO
 eruption.conf(5), eruptionctl(1), eruption-netfx(1)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
