.\" Manpage for Eruption.
.TH man 1 "Dec 2022" "0.0.1" "eruption-fx-proxy man page"
.SH NAME
  eruption-fx-proxy - Effects proxy daemon for the Eruption Linux user-mode driver
.SH SYNOPSIS
.BR

  Usage: eruption-fx-proxy [OPTIONS] <COMMAND>

.SH DESCRIPTION
.BR

  Commands:
    daemon       Run in background
    help         Print this message or the help of the given subcommand(s)

  Options:
    -v, --verbose...       Verbose mode (-v, -vv, -vvv, etc.)
    -c, --config <CONFIG>  Sets the configuration file to use
    -h, --help             Print help information
    -V, --version          Print version information


.SH SEE ALSO
  eruption(8), eruption.conf(5)
.SH BUGS
  No known bugs
.SH AUTHOR
  X3n0m0rph59 <x3n0m0rph59@gmail.com>
