.\" Manpage for Eruption.
.TH man 5 "Nov 2020" "0.0.1" "process-monitor.conf man page"
.SH NAME
 eruption-process-monitor - A daemon to monitor and introspect system processes and events
.SH SYNOPSIS
.SH DESCRIPTION

.br
 [global]
 enable_experimental_features = true
.br
.br
 [X11]
 display = ":1"
.br

.SH SEE ALSO
 eruption(8), eruptionctl(1), eruption-process-monitor(1)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
