.\" Manpage for Eruption.
.TH man 1 "Sep 2023" "0.0.3" "pyroclasm man page"
.SH NAME
  pyroclasm - Pyroclasm UI for Eruption

.SH SYNOPSIS
.BR

  Usage: pyroclasm [OPTIONS] <COMMAND>

.SH DESCRIPTION
.BR

  Commands:
    help           Print this message or the help of the given subcommand(s)

  Options:
    -v, --verbose...       Verbose mode (-v, -vv, -vvv, etc.)
    -c, --config <CONFIG>  Sets the configuration file to use
    -h, --help             Print help information
    -V, --version          Print version information


.SH SEE ALSO
  eruption(8), eruption.conf(5), eruption-keymap(1), eruption-macro(1), eruption-netfx(1)
.SH BUGS
  No known bugs
.SH AUTHOR
  X3n0m0rph59 <x3n0m0rph59@gmail.com>
