/*
    This file is part of Eruption.

    Eruption is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Eruption is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Eruption.  If not, see <http://www.gnu.org/licenses/>.

    Copyright (c) 2019-2022, The Eruption Development Team
*/

#![allow(unused)]

use std::io;

use evdev_rs::enums::{int_to_ev_key, EventCode, EV_KEY};
use io::Write;
use maplit::hashmap;

use crate::{
    dbus_client::get_managed_devices,
    device::{get_device_info, DeviceInfo},
    hwdevices,
};

#[allow(unused)]
type Result<T> = std::result::Result<T, eyre::Error>;

#[derive(Debug, thiserror::Error)]
pub enum UtilError {
    #[error("Invalid parameter")]
    InvalidParameter {},

    #[error("Device not found")]
    DeviceNotFound {},
}

pub fn get_input(prompt: &str) -> io::Result<String> {
    print!("{}", prompt);
    io::stdout().lock().flush()?;

    let mut input = String::new();
    io::stdin().read_line(&mut input)?;

    Ok(input.trim().to_string())
}

pub fn get_device_info_from_index(device: u64) -> Option<&'static DeviceInfo> {
    let mut base_index = 0;

    let (keyboards, mice, misc) = get_managed_devices().expect("Could not get device information");

    if !keyboards.is_empty() {
        for (_index, dev) in keyboards.iter().enumerate() {
            if base_index == device {
                return get_device_info(dev.0, dev.1);
            }

            base_index += 1;
        }
    }

    if !mice.is_empty() {
        for (_index, dev) in mice.iter().enumerate() {
            if base_index == device {
                return get_device_info(dev.0, dev.1);
            }

            base_index += 1;
        }
    }

    if !misc.is_empty() {
        for (_index, dev) in misc.iter().enumerate() {
            if base_index == device {
                return get_device_info(dev.0, dev.1);
            }

            base_index += 1;
        }
    }

    None
}

pub fn evdev_event_code_to_string(event: u32) -> String {
    let map = hashmap! {
        EV_KEY::KEY_RESERVED => "KEY_RESERVED",
        EV_KEY::KEY_ESC => "KEY_ESC",
        EV_KEY::KEY_1 => "KEY_1",
        EV_KEY::KEY_2 => "KEY_2",
        EV_KEY::KEY_3 => "KEY_3",
        EV_KEY::KEY_4 => "KEY_4",
        EV_KEY::KEY_5 => "KEY_5",
        EV_KEY::KEY_6 => "KEY_6",
        EV_KEY::KEY_7 => "KEY_7",
        EV_KEY::KEY_8 => "KEY_8",
        EV_KEY::KEY_9 => "KEY_9",
        EV_KEY::KEY_0 => "KEY_0",
        EV_KEY::KEY_MINUS => "KEY_MINUS",
        EV_KEY::KEY_EQUAL => "KEY_EQUAL",
        EV_KEY::KEY_BACKSPACE => "KEY_BACKSPACE",
        EV_KEY::KEY_TAB => "KEY_TAB",
        EV_KEY::KEY_Q => "KEY_Q",
        EV_KEY::KEY_W => "KEY_W",
        EV_KEY::KEY_E => "KEY_E",
        EV_KEY::KEY_R => "KEY_R",
        EV_KEY::KEY_T => "KEY_T",
        EV_KEY::KEY_Y => "KEY_Y",
        EV_KEY::KEY_U => "KEY_U",
        EV_KEY::KEY_I => "KEY_I",
        EV_KEY::KEY_O => "KEY_O",
        EV_KEY::KEY_P => "KEY_P",
        EV_KEY::KEY_LEFTBRACE => "KEY_LEFTBRACE",
        EV_KEY::KEY_RIGHTBRACE => "KEY_RIGHTBRACE",
        EV_KEY::KEY_ENTER => "KEY_ENTER",
        EV_KEY::KEY_LEFTCTRL => "KEY_LEFTCTRL",
        EV_KEY::KEY_A => "KEY_A",
        EV_KEY::KEY_S => "KEY_S",
        EV_KEY::KEY_D => "KEY_D",
        EV_KEY::KEY_F => "KEY_F",
        EV_KEY::KEY_G => "KEY_G",
        EV_KEY::KEY_H => "KEY_H",
        EV_KEY::KEY_J => "KEY_J",
        EV_KEY::KEY_K => "KEY_K",
        EV_KEY::KEY_L => "KEY_L",
        EV_KEY::KEY_SEMICOLON => "KEY_SEMICOLON",
        EV_KEY::KEY_APOSTROPHE => "KEY_APOSTROPHE",
        EV_KEY::KEY_GRAVE => "KEY_GRAVE",
        EV_KEY::KEY_LEFTSHIFT => "KEY_LEFTSHIFT",
        EV_KEY::KEY_BACKSLASH => "KEY_BACKSLASH",
        EV_KEY::KEY_Z => "KEY_Z",
        EV_KEY::KEY_X => "KEY_X",
        EV_KEY::KEY_C => "KEY_C",
        EV_KEY::KEY_V => "KEY_V",
        EV_KEY::KEY_B => "KEY_B",
        EV_KEY::KEY_N => "KEY_N",
        EV_KEY::KEY_M => "KEY_M",
        EV_KEY::KEY_COMMA => "KEY_COMMA",
        EV_KEY::KEY_DOT => "KEY_DOT",
        EV_KEY::KEY_SLASH => "KEY_SLASH",
        EV_KEY::KEY_RIGHTSHIFT => "KEY_RIGHTSHIFT",
        EV_KEY::KEY_KPASTERISK => "KEY_KPASTERISK",
        EV_KEY::KEY_LEFTALT => "KEY_LEFTALT",
        EV_KEY::KEY_SPACE => "KEY_SPACE",
        EV_KEY::KEY_CAPSLOCK => "KEY_CAPSLOCK",
        EV_KEY::KEY_F1 => "KEY_F1",
        EV_KEY::KEY_F2 => "KEY_F2",
        EV_KEY::KEY_F3 => "KEY_F3",
        EV_KEY::KEY_F4 => "KEY_F4",
        EV_KEY::KEY_F5 => "KEY_F5",
        EV_KEY::KEY_F6 => "KEY_F6",
        EV_KEY::KEY_F7 => "KEY_F7",
        EV_KEY::KEY_F8 => "KEY_F8",
        EV_KEY::KEY_F9 => "KEY_F9",
        EV_KEY::KEY_F10 => "KEY_F10",
        EV_KEY::KEY_NUMLOCK => "KEY_NUMLOCK",
        EV_KEY::KEY_SCROLLLOCK => "KEY_SCROLLLOCK",
        EV_KEY::KEY_KP7 => "KEY_KP7",
        EV_KEY::KEY_KP8 => "KEY_KP8",
        EV_KEY::KEY_KP9 => "KEY_KP9",
        EV_KEY::KEY_KPMINUS => "KEY_KPMINUS",
        EV_KEY::KEY_KP4 => "KEY_KP4",
        EV_KEY::KEY_KP5 => "KEY_KP5",
        EV_KEY::KEY_KP6 => "KEY_KP6",
        EV_KEY::KEY_KPPLUS => "KEY_KPPLUS",
        EV_KEY::KEY_KP1 => "KEY_KP1",
        EV_KEY::KEY_KP2 => "KEY_KP2",
        EV_KEY::KEY_KP3 => "KEY_KP3",
        EV_KEY::KEY_KP0 => "KEY_KP0",
        EV_KEY::KEY_KPDOT => "KEY_KPDOT",
        EV_KEY::KEY_ZENKAKUHANKAKU => "KEY_ZENKAKUHANKAKU",
        EV_KEY::KEY_102ND => "KEY_102ND",
        EV_KEY::KEY_F11 => "KEY_F11",
        EV_KEY::KEY_F12 => "KEY_F12",
        EV_KEY::KEY_RO => "KEY_RO",
        EV_KEY::KEY_KATAKANA => "KEY_KATAKANA",
        EV_KEY::KEY_HIRAGANA => "KEY_HIRAGANA",
        EV_KEY::KEY_HENKAN => "KEY_HENKAN",
        EV_KEY::KEY_KATAKANAHIRAGANA => "KEY_KATAKANAHIRAGANA",
        EV_KEY::KEY_MUHENKAN => "KEY_MUHENKAN",
        EV_KEY::KEY_KPJPCOMMA => "KEY_KPJPCOMMA",
        EV_KEY::KEY_KPENTER => "KEY_KPENTER",
        EV_KEY::KEY_RIGHTCTRL => "KEY_RIGHTCTRL",
        EV_KEY::KEY_KPSLASH => "KEY_KPSLASH",
        EV_KEY::KEY_SYSRQ => "KEY_SYSRQ",
        EV_KEY::KEY_RIGHTALT => "KEY_RIGHTALT",
        EV_KEY::KEY_LINEFEED => "KEY_LINEFEED",
        EV_KEY::KEY_HOME => "KEY_HOME",
        EV_KEY::KEY_UP => "KEY_UP",
        EV_KEY::KEY_PAGEUP => "KEY_PAGEUP",
        EV_KEY::KEY_LEFT => "KEY_LEFT",
        EV_KEY::KEY_RIGHT => "KEY_RIGHT",
        EV_KEY::KEY_END => "KEY_END",
        EV_KEY::KEY_DOWN => "KEY_DOWN",
        EV_KEY::KEY_PAGEDOWN => "KEY_PAGEDOWN",
        EV_KEY::KEY_INSERT => "KEY_INSERT",
        EV_KEY::KEY_DELETE => "KEY_DELETE",
        EV_KEY::KEY_MACRO => "KEY_MACRO",
        EV_KEY::KEY_MUTE => "KEY_MUTE",
        EV_KEY::KEY_VOLUMEDOWN => "KEY_VOLUMEDOWN",
        EV_KEY::KEY_VOLUMEUP => "KEY_VOLUMEUP",
        EV_KEY::KEY_POWER => "KEY_POWER",
        EV_KEY::KEY_KPEQUAL => "KEY_KPEQUAL",
        EV_KEY::KEY_KPPLUSMINUS => "KEY_KPPLUSMINUS",
        EV_KEY::KEY_PAUSE => "KEY_PAUSE",
        EV_KEY::KEY_SCALE => "KEY_SCALE",
        EV_KEY::KEY_KPCOMMA => "KEY_KPCOMMA",
        EV_KEY::KEY_HANGEUL => "KEY_HANGEUL",
        EV_KEY::KEY_HANJA => "KEY_HANJA",
        EV_KEY::KEY_YEN => "KEY_YEN",
        EV_KEY::KEY_LEFTMETA => "KEY_LEFTMETA",
        EV_KEY::KEY_RIGHTMETA => "KEY_RIGHTMETA",
        EV_KEY::KEY_COMPOSE => "KEY_COMPOSE",
        EV_KEY::KEY_STOP => "KEY_STOP",
        EV_KEY::KEY_AGAIN => "KEY_AGAIN",
        EV_KEY::KEY_PROPS => "KEY_PROPS",
        EV_KEY::KEY_UNDO => "KEY_UNDO",
        EV_KEY::KEY_FRONT => "KEY_FRONT",
        EV_KEY::KEY_COPY => "KEY_COPY",
        EV_KEY::KEY_OPEN => "KEY_OPEN",
        EV_KEY::KEY_PASTE => "KEY_PASTE",
        EV_KEY::KEY_FIND => "KEY_FIND",
        EV_KEY::KEY_CUT => "KEY_CUT",
        EV_KEY::KEY_HELP => "KEY_HELP",
        EV_KEY::KEY_MENU => "KEY_MENU",
        EV_KEY::KEY_CALC => "KEY_CALC",
        EV_KEY::KEY_SETUP => "KEY_SETUP",
        EV_KEY::KEY_SLEEP => "KEY_SLEEP",
        EV_KEY::KEY_WAKEUP => "KEY_WAKEUP",
        EV_KEY::KEY_FILE => "KEY_FILE",
        EV_KEY::KEY_SENDFILE => "KEY_SENDFILE",
        EV_KEY::KEY_DELETEFILE => "KEY_DELETEFILE",
        EV_KEY::KEY_XFER => "KEY_XFER",
        EV_KEY::KEY_PROG1 => "KEY_PROG1",
        EV_KEY::KEY_PROG2 => "KEY_PROG2",
        EV_KEY::KEY_WWW => "KEY_WWW",
        EV_KEY::KEY_MSDOS => "KEY_MSDOS",
        EV_KEY::KEY_COFFEE => "KEY_COFFEE",
        EV_KEY::KEY_ROTATE_DISPLAY => "KEY_ROTATE_DISPLAY",
        EV_KEY::KEY_CYCLEWINDOWS => "KEY_CYCLEWINDOWS",
        EV_KEY::KEY_MAIL => "KEY_MAIL",
        EV_KEY::KEY_BOOKMARKS => "KEY_BOOKMARKS",
        EV_KEY::KEY_COMPUTER => "KEY_COMPUTER",
        EV_KEY::KEY_BACK => "KEY_BACK",
        EV_KEY::KEY_FORWARD => "KEY_FORWARD",
        EV_KEY::KEY_CLOSECD => "KEY_CLOSECD",
        EV_KEY::KEY_EJECTCD => "KEY_EJECTCD",
        EV_KEY::KEY_EJECTCLOSECD => "KEY_EJECTCLOSECD",
        EV_KEY::KEY_NEXTSONG => "KEY_NEXTSONG",
        EV_KEY::KEY_PLAYPAUSE => "KEY_PLAYPAUSE",
        EV_KEY::KEY_PREVIOUSSONG => "KEY_PREVIOUSSONG",
        EV_KEY::KEY_STOPCD => "KEY_STOPCD",
        EV_KEY::KEY_RECORD => "KEY_RECORD",
        EV_KEY::KEY_REWIND => "KEY_REWIND",
        EV_KEY::KEY_PHONE => "KEY_PHONE",
        EV_KEY::KEY_ISO => "KEY_ISO",
        EV_KEY::KEY_CONFIG => "KEY_CONFIG",
        EV_KEY::KEY_HOMEPAGE => "KEY_HOMEPAGE",
        EV_KEY::KEY_REFRESH => "KEY_REFRESH",
        EV_KEY::KEY_EXIT => "KEY_EXIT",
        EV_KEY::KEY_MOVE => "KEY_MOVE",
        EV_KEY::KEY_EDIT => "KEY_EDIT",
        EV_KEY::KEY_SCROLLUP => "KEY_SCROLLUP",
        EV_KEY::KEY_SCROLLDOWN => "KEY_SCROLLDOWN",
        EV_KEY::KEY_KPLEFTPAREN => "KEY_KPLEFTPAREN",
        EV_KEY::KEY_KPRIGHTPAREN => "KEY_KPRIGHTPAREN",
        EV_KEY::KEY_NEW => "KEY_NEW",
        EV_KEY::KEY_REDO => "KEY_REDO",
        EV_KEY::KEY_F13 => "KEY_F13",
        EV_KEY::KEY_F14 => "KEY_F14",
        EV_KEY::KEY_F15 => "KEY_F15",
        EV_KEY::KEY_F16 => "KEY_F16",
        EV_KEY::KEY_F17 => "KEY_F17",
        EV_KEY::KEY_F18 => "KEY_F18",
        EV_KEY::KEY_F19 => "KEY_F19",
        EV_KEY::KEY_F20 => "KEY_F20",
        EV_KEY::KEY_F21 => "KEY_F21",
        EV_KEY::KEY_F22 => "KEY_F22",
        EV_KEY::KEY_F23 => "KEY_F23",
        EV_KEY::KEY_F24 => "KEY_F24",
        EV_KEY::KEY_PLAYCD => "KEY_PLAYCD",
        EV_KEY::KEY_PAUSECD => "KEY_PAUSECD",
        EV_KEY::KEY_PROG3 => "KEY_PROG3",
        EV_KEY::KEY_PROG4 => "KEY_PROG4",
        EV_KEY::KEY_SUSPEND => "KEY_SUSPEND",
        EV_KEY::KEY_CLOSE => "KEY_CLOSE",
        EV_KEY::KEY_PLAY => "KEY_PLAY",
        EV_KEY::KEY_FASTFORWARD => "KEY_FASTFORWARD",
        EV_KEY::KEY_BASSBOOST => "KEY_BASSBOOST",
        EV_KEY::KEY_PRINT => "KEY_PRINT",
        EV_KEY::KEY_HP => "KEY_HP",
        EV_KEY::KEY_CAMERA => "KEY_CAMERA",
        EV_KEY::KEY_SOUND => "KEY_SOUND",
        EV_KEY::KEY_QUESTION => "KEY_QUESTION",
        EV_KEY::KEY_EMAIL => "KEY_EMAIL",
        EV_KEY::KEY_CHAT => "KEY_CHAT",
        EV_KEY::KEY_SEARCH => "KEY_SEARCH",
        EV_KEY::KEY_CONNECT => "KEY_CONNECT",
        EV_KEY::KEY_FINANCE => "KEY_FINANCE",
        EV_KEY::KEY_SPORT => "KEY_SPORT",
        EV_KEY::KEY_SHOP => "KEY_SHOP",
        EV_KEY::KEY_ALTERASE => "KEY_ALTERASE",
        EV_KEY::KEY_CANCEL => "KEY_CANCEL",
        EV_KEY::KEY_BRIGHTNESSDOWN => "KEY_BRIGHTNESSDOWN",
        EV_KEY::KEY_BRIGHTNESSUP => "KEY_BRIGHTNESSUP",
        EV_KEY::KEY_MEDIA => "KEY_MEDIA",
        EV_KEY::KEY_SWITCHVIDEOMODE => "KEY_SWITCHVIDEOMODE",
        EV_KEY::KEY_KBDILLUMTOGGLE => "KEY_KBDILLUMTOGGLE",
        EV_KEY::KEY_KBDILLUMDOWN => "KEY_KBDILLUMDOWN",
        EV_KEY::KEY_KBDILLUMUP => "KEY_KBDILLUMUP",
        EV_KEY::KEY_SEND => "KEY_SEND",
        EV_KEY::KEY_REPLY => "KEY_REPLY",
        EV_KEY::KEY_FORWARDMAIL => "KEY_FORWARDMAIL",
        EV_KEY::KEY_SAVE => "KEY_SAVE",
        EV_KEY::KEY_DOCUMENTS => "KEY_DOCUMENTS",
        EV_KEY::KEY_BATTERY => "KEY_BATTERY",
        EV_KEY::KEY_BLUETOOTH => "KEY_BLUETOOTH",
        EV_KEY::KEY_WLAN => "KEY_WLAN",
        EV_KEY::KEY_UWB => "KEY_UWB",
        EV_KEY::KEY_UNKNOWN => "KEY_UNKNOWN",
        EV_KEY::KEY_VIDEO_NEXT => "KEY_VIDEO_NEXT",
        EV_KEY::KEY_VIDEO_PREV => "KEY_VIDEO_PREV",
        EV_KEY::KEY_BRIGHTNESS_CYCLE => "KEY_BRIGHTNESS_CYCLE",
        EV_KEY::KEY_BRIGHTNESS_AUTO => "KEY_BRIGHTNESS_AUTO",
        EV_KEY::KEY_DISPLAY_OFF => "KEY_DISPLAY_OFF",
        EV_KEY::KEY_WWAN => "KEY_WWAN",
        EV_KEY::KEY_RFKILL => "KEY_RFKILL",
        EV_KEY::KEY_MICMUTE => "KEY_MICMUTE",
        EV_KEY::KEY_OK => "KEY_OK",
        EV_KEY::KEY_SELECT => "KEY_SELECT",
        EV_KEY::KEY_GOTO => "KEY_GOTO",
        EV_KEY::KEY_CLEAR => "KEY_CLEAR",
        EV_KEY::KEY_POWER2 => "KEY_POWER2",
        EV_KEY::KEY_OPTION => "KEY_OPTION",
        EV_KEY::KEY_INFO => "KEY_INFO",
        EV_KEY::KEY_TIME => "KEY_TIME",
        EV_KEY::KEY_VENDOR => "KEY_VENDOR",
        EV_KEY::KEY_ARCHIVE => "KEY_ARCHIVE",
        EV_KEY::KEY_PROGRAM => "KEY_PROGRAM",
        EV_KEY::KEY_CHANNEL => "KEY_CHANNEL",
        EV_KEY::KEY_FAVORITES => "KEY_FAVORITES",
        EV_KEY::KEY_EPG => "KEY_EPG",
        EV_KEY::KEY_PVR => "KEY_PVR",
        EV_KEY::KEY_MHP => "KEY_MHP",
        EV_KEY::KEY_LANGUAGE => "KEY_LANGUAGE",
        EV_KEY::KEY_TITLE => "KEY_TITLE",
        EV_KEY::KEY_SUBTITLE => "KEY_SUBTITLE",
        EV_KEY::KEY_ANGLE => "KEY_ANGLE",
        EV_KEY::KEY_FULL_SCREEN => "KEY_FULL_SCREEN",
        EV_KEY::KEY_MODE => "KEY_MODE",
        EV_KEY::KEY_KEYBOARD => "KEY_KEYBOARD",
        EV_KEY::KEY_ASPECT_RATIO => "KEY_ASPECT_RATIO",
        EV_KEY::KEY_PC => "KEY_PC",
        EV_KEY::KEY_TV => "KEY_TV",
        EV_KEY::KEY_TV2 => "KEY_TV2",
        EV_KEY::KEY_VCR => "KEY_VCR",
        EV_KEY::KEY_VCR2 => "KEY_VCR2",
        EV_KEY::KEY_SAT => "KEY_SAT",
        EV_KEY::KEY_SAT2 => "KEY_SAT2",
        EV_KEY::KEY_CD => "KEY_CD",
        EV_KEY::KEY_TAPE => "KEY_TAPE",
        EV_KEY::KEY_RADIO => "KEY_RADIO",
        EV_KEY::KEY_TUNER => "KEY_TUNER",
        EV_KEY::KEY_PLAYER => "KEY_PLAYER",
        EV_KEY::KEY_TEXT => "KEY_TEXT",
        EV_KEY::KEY_DVD => "KEY_DVD",
        EV_KEY::KEY_AUX => "KEY_AUX",
        EV_KEY::KEY_MP3 => "KEY_MP3",
        EV_KEY::KEY_AUDIO => "KEY_AUDIO",
        EV_KEY::KEY_VIDEO => "KEY_VIDEO",
        EV_KEY::KEY_DIRECTORY => "KEY_DIRECTORY",
        EV_KEY::KEY_LIST => "KEY_LIST",
        EV_KEY::KEY_MEMO => "KEY_MEMO",
        EV_KEY::KEY_CALENDAR => "KEY_CALENDAR",
        EV_KEY::KEY_RED => "KEY_RED",
        EV_KEY::KEY_GREEN => "KEY_GREEN",
        EV_KEY::KEY_YELLOW => "KEY_YELLOW",
        EV_KEY::KEY_BLUE => "KEY_BLUE",
        EV_KEY::KEY_CHANNELUP => "KEY_CHANNELUP",
        EV_KEY::KEY_CHANNELDOWN => "KEY_CHANNELDOWN",
        EV_KEY::KEY_FIRST => "KEY_FIRST",
        EV_KEY::KEY_LAST => "KEY_LAST",
        EV_KEY::KEY_AB => "KEY_AB",
        EV_KEY::KEY_NEXT => "KEY_NEXT",
        EV_KEY::KEY_RESTART => "KEY_RESTART",
        EV_KEY::KEY_SLOW => "KEY_SLOW",
        EV_KEY::KEY_SHUFFLE => "KEY_SHUFFLE",
        EV_KEY::KEY_BREAK => "KEY_BREAK",
        EV_KEY::KEY_PREVIOUS => "KEY_PREVIOUS",
        EV_KEY::KEY_DIGITS => "KEY_DIGITS",
        EV_KEY::KEY_TEEN => "KEY_TEEN",
        EV_KEY::KEY_TWEN => "KEY_TWEN",
        EV_KEY::KEY_VIDEOPHONE => "KEY_VIDEOPHONE",
        EV_KEY::KEY_GAMES => "KEY_GAMES",
        EV_KEY::KEY_ZOOMIN => "KEY_ZOOMIN",
        EV_KEY::KEY_ZOOMOUT => "KEY_ZOOMOUT",
        EV_KEY::KEY_ZOOMRESET => "KEY_ZOOMRESET",
        EV_KEY::KEY_WORDPROCESSOR => "KEY_WORDPROCESSOR",
        EV_KEY::KEY_EDITOR => "KEY_EDITOR",
        EV_KEY::KEY_SPREADSHEET => "KEY_SPREADSHEET",
        EV_KEY::KEY_GRAPHICSEDITOR => "KEY_GRAPHICSEDITOR",
        EV_KEY::KEY_PRESENTATION => "KEY_PRESENTATION",
        EV_KEY::KEY_DATABASE => "KEY_DATABASE",
        EV_KEY::KEY_NEWS => "KEY_NEWS",
        EV_KEY::KEY_VOICEMAIL => "KEY_VOICEMAIL",
        EV_KEY::KEY_ADDRESSBOOK => "KEY_ADDRESSBOOK",
        EV_KEY::KEY_MESSENGER => "KEY_MESSENGER",
        EV_KEY::KEY_DISPLAYTOGGLE => "KEY_DISPLAYTOGGLE",
        EV_KEY::KEY_SPELLCHECK => "KEY_SPELLCHECK",
        EV_KEY::KEY_LOGOFF => "KEY_LOGOFF",
        EV_KEY::KEY_DOLLAR => "KEY_DOLLAR",
        EV_KEY::KEY_EURO => "KEY_EURO",
        EV_KEY::KEY_FRAMEBACK => "KEY_FRAMEBACK",
        EV_KEY::KEY_FRAMEFORWARD => "KEY_FRAMEFORWARD",
        EV_KEY::KEY_CONTEXT_MENU => "KEY_CONTEXT_MENU",
        EV_KEY::KEY_MEDIA_REPEAT => "KEY_MEDIA_REPEAT",
        EV_KEY::KEY_10CHANNELSUP => "KEY_10CHANNELSUP",
        EV_KEY::KEY_10CHANNELSDOWN => "KEY_10CHANNELSDOWN",
        EV_KEY::KEY_IMAGES => "KEY_IMAGES",
        EV_KEY::KEY_DEL_EOL => "KEY_DEL_EOL",
        EV_KEY::KEY_DEL_EOS => "KEY_DEL_EOS",
        EV_KEY::KEY_INS_LINE => "KEY_INS_LINE",
        EV_KEY::KEY_DEL_LINE => "KEY_DEL_LINE",
        EV_KEY::KEY_FN => "KEY_FN",
        EV_KEY::KEY_FN_ESC => "KEY_FN_ESC",
        EV_KEY::KEY_FN_F1 => "KEY_FN_F1",
        EV_KEY::KEY_FN_F2 => "KEY_FN_F2",
        EV_KEY::KEY_FN_F3 => "KEY_FN_F3",
        EV_KEY::KEY_FN_F4 => "KEY_FN_F4",
        EV_KEY::KEY_FN_F5 => "KEY_FN_F5",
        EV_KEY::KEY_FN_F6 => "KEY_FN_F6",
        EV_KEY::KEY_FN_F7 => "KEY_FN_F7",
        EV_KEY::KEY_FN_F8 => "KEY_FN_F8",
        EV_KEY::KEY_FN_F9 => "KEY_FN_F9",
        EV_KEY::KEY_FN_F10 => "KEY_FN_F10",
        EV_KEY::KEY_FN_F11 => "KEY_FN_F11",
        EV_KEY::KEY_FN_F12 => "KEY_FN_F12",
        EV_KEY::KEY_FN_1 => "KEY_FN_1",
        EV_KEY::KEY_FN_2 => "KEY_FN_2",
        EV_KEY::KEY_FN_D => "KEY_FN_D",
        EV_KEY::KEY_FN_E => "KEY_FN_E",
        EV_KEY::KEY_FN_F => "KEY_FN_F",
        EV_KEY::KEY_FN_S => "KEY_FN_S",
        EV_KEY::KEY_FN_B => "KEY_FN_B",
        EV_KEY::KEY_BRL_DOT1 => "KEY_BRL_DOT1",
        EV_KEY::KEY_BRL_DOT2 => "KEY_BRL_DOT2",
        EV_KEY::KEY_BRL_DOT3 => "KEY_BRL_DOT3",
        EV_KEY::KEY_BRL_DOT4 => "KEY_BRL_DOT4",
        EV_KEY::KEY_BRL_DOT5 => "KEY_BRL_DOT5",
        EV_KEY::KEY_BRL_DOT6 => "KEY_BRL_DOT6",
        EV_KEY::KEY_BRL_DOT7 => "KEY_BRL_DOT7",
        EV_KEY::KEY_BRL_DOT8 => "KEY_BRL_DOT8",
        EV_KEY::KEY_BRL_DOT9 => "KEY_BRL_DOT9",
        EV_KEY::KEY_BRL_DOT10 => "KEY_BRL_DOT10",
        EV_KEY::KEY_NUMERIC_0 => "KEY_NUMERIC_0",
        EV_KEY::KEY_NUMERIC_1 => "KEY_NUMERIC_1",
        EV_KEY::KEY_NUMERIC_2 => "KEY_NUMERIC_2",
        EV_KEY::KEY_NUMERIC_3 => "KEY_NUMERIC_3",
        EV_KEY::KEY_NUMERIC_4 => "KEY_NUMERIC_4",
        EV_KEY::KEY_NUMERIC_5 => "KEY_NUMERIC_5",
        EV_KEY::KEY_NUMERIC_6 => "KEY_NUMERIC_6",
        EV_KEY::KEY_NUMERIC_7 => "KEY_NUMERIC_7",
        EV_KEY::KEY_NUMERIC_8 => "KEY_NUMERIC_8",
        EV_KEY::KEY_NUMERIC_9 => "KEY_NUMERIC_9",
        EV_KEY::KEY_NUMERIC_STAR => "KEY_NUMERIC_STAR",
        EV_KEY::KEY_NUMERIC_POUND => "KEY_NUMERIC_POUND",
        EV_KEY::KEY_NUMERIC_A => "KEY_NUMERIC_A",
        EV_KEY::KEY_NUMERIC_B => "KEY_NUMERIC_B",
        EV_KEY::KEY_NUMERIC_C => "KEY_NUMERIC_C",
        EV_KEY::KEY_NUMERIC_D => "KEY_NUMERIC_D",
        EV_KEY::KEY_CAMERA_FOCUS => "KEY_CAMERA_FOCUS",
        EV_KEY::KEY_WPS_BUTTON => "KEY_WPS_BUTTON",
        EV_KEY::KEY_TOUCHPAD_TOGGLE => "KEY_TOUCHPAD_TOGGLE",
        EV_KEY::KEY_TOUCHPAD_ON => "KEY_TOUCHPAD_ON",
        EV_KEY::KEY_TOUCHPAD_OFF => "KEY_TOUCHPAD_OFF",
        EV_KEY::KEY_CAMERA_ZOOMIN => "KEY_CAMERA_ZOOMIN",
        EV_KEY::KEY_CAMERA_ZOOMOUT => "KEY_CAMERA_ZOOMOUT",
        EV_KEY::KEY_CAMERA_UP => "KEY_CAMERA_UP",
        EV_KEY::KEY_CAMERA_DOWN => "KEY_CAMERA_DOWN",
        EV_KEY::KEY_CAMERA_LEFT => "KEY_CAMERA_LEFT",
        EV_KEY::KEY_CAMERA_RIGHT => "KEY_CAMERA_RIGHT",
        EV_KEY::KEY_ATTENDANT_ON => "KEY_ATTENDANT_ON",
        EV_KEY::KEY_ATTENDANT_OFF => "KEY_ATTENDANT_OFF",
        EV_KEY::KEY_ATTENDANT_TOGGLE => "KEY_ATTENDANT_TOGGLE",
        EV_KEY::KEY_LIGHTS_TOGGLE => "KEY_LIGHTS_TOGGLE",
        EV_KEY::KEY_ALS_TOGGLE => "KEY_ALS_TOGGLE",
        EV_KEY::KEY_ROTATE_LOCK_TOGGLE => "KEY_ROTATE_LOCK_TOGGLE",
        EV_KEY::KEY_BUTTONCONFIG => "KEY_BUTTONCONFIG",
        EV_KEY::KEY_TASKMANAGER => "KEY_TASKMANAGER",
        EV_KEY::KEY_JOURNAL => "KEY_JOURNAL",
        EV_KEY::KEY_CONTROLPANEL => "KEY_CONTROLPANEL",
        EV_KEY::KEY_APPSELECT => "KEY_APPSELECT",
        EV_KEY::KEY_SCREENSAVER => "KEY_SCREENSAVER",
        EV_KEY::KEY_VOICECOMMAND => "KEY_VOICECOMMAND",
        EV_KEY::KEY_ASSISTANT => "KEY_ASSISTANT",
        EV_KEY::KEY_KBD_LAYOUT_NEXT => "KEY_KBD_LAYOUT_NEXT",
        EV_KEY::KEY_BRIGHTNESS_MIN => "KEY_BRIGHTNESS_MIN",
        EV_KEY::KEY_BRIGHTNESS_MAX => "KEY_BRIGHTNESS_MAX",
        EV_KEY::KEY_KBDINPUTASSIST_PREV => "KEY_KBDINPUTASSIST_PREV",
        EV_KEY::KEY_KBDINPUTASSIST_NEXT => "KEY_KBDINPUTASSIST_NEXT",
        EV_KEY::KEY_KBDINPUTASSIST_PREVGROUP => "KEY_KBDINPUTASSIST_PREVGROUP",
        EV_KEY::KEY_KBDINPUTASSIST_NEXTGROUP => "KEY_KBDINPUTASSIST_NEXTGROUP",
        EV_KEY::KEY_KBDINPUTASSIST_ACCEPT => "KEY_KBDINPUTASSIST_ACCEPT",
        EV_KEY::KEY_KBDINPUTASSIST_CANCEL => "KEY_KBDINPUTASSIST_CANCEL",
        EV_KEY::KEY_RIGHT_UP => "KEY_RIGHT_UP",
        EV_KEY::KEY_RIGHT_DOWN => "KEY_RIGHT_DOWN",
        EV_KEY::KEY_LEFT_UP => "KEY_LEFT_UP",
        EV_KEY::KEY_LEFT_DOWN => "KEY_LEFT_DOWN",
        EV_KEY::KEY_ROOT_MENU => "KEY_ROOT_MENU",
        EV_KEY::KEY_MEDIA_TOP_MENU => "KEY_MEDIA_TOP_MENU",
        EV_KEY::KEY_NUMERIC_11 => "KEY_NUMERIC_11",
        EV_KEY::KEY_NUMERIC_12 => "KEY_NUMERIC_12",
        EV_KEY::KEY_AUDIO_DESC => "KEY_AUDIO_DESC",
        EV_KEY::KEY_3D_MODE => "KEY_3D_MODE",
        EV_KEY::KEY_NEXT_FAVORITE => "KEY_NEXT_FAVORITE",
        EV_KEY::KEY_STOP_RECORD => "KEY_STOP_RECORD",
        EV_KEY::KEY_PAUSE_RECORD => "KEY_PAUSE_RECORD",
        EV_KEY::KEY_VOD => "KEY_VOD",
        EV_KEY::KEY_UNMUTE => "KEY_UNMUTE",
        EV_KEY::KEY_FASTREVERSE => "KEY_FASTREVERSE",
        EV_KEY::KEY_SLOWREVERSE => "KEY_SLOWREVERSE",
        EV_KEY::KEY_DATA => "KEY_DATA",
        EV_KEY::KEY_ONSCREEN_KEYBOARD => "KEY_ONSCREEN_KEYBOARD",
        EV_KEY::KEY_MAX => "KEY_MAX",
    };

    match int_to_evdev_key_event(event) {
        Some(event) => map
            .get(&event)
            .unwrap_or(&"<Invalid evdev event code>")
            .to_string(),
        None => "<Invalid evdev event code>".to_string(),
    }
}

pub fn evdev_event_code_from_string(event: &str) -> Option<EV_KEY> {
    let map = hashmap! {
        "KEY_RESERVED" => EV_KEY::KEY_RESERVED,
        "KEY_ESC" => EV_KEY::KEY_ESC,
        "KEY_1" => EV_KEY::KEY_1,
        "KEY_2" => EV_KEY::KEY_2,
        "KEY_3" => EV_KEY::KEY_3,
        "KEY_4" => EV_KEY::KEY_4,
        "KEY_5" => EV_KEY::KEY_5,
        "KEY_6" => EV_KEY::KEY_6,
        "KEY_7" => EV_KEY::KEY_7,
        "KEY_8" => EV_KEY::KEY_8,
        "KEY_9" => EV_KEY::KEY_9,
        "KEY_0" => EV_KEY::KEY_0,
        "KEY_MINUS" => EV_KEY::KEY_MINUS,
        "KEY_EQUAL" => EV_KEY::KEY_EQUAL,
        "KEY_BACKSPACE" => EV_KEY::KEY_BACKSPACE,
        "KEY_TAB" => EV_KEY::KEY_TAB,
        "KEY_Q" => EV_KEY::KEY_Q,
        "KEY_W" => EV_KEY::KEY_W,
        "KEY_E" => EV_KEY::KEY_E,
        "KEY_R" => EV_KEY::KEY_R,
        "KEY_T" => EV_KEY::KEY_T,
        "KEY_Y" => EV_KEY::KEY_Y,
        "KEY_U" => EV_KEY::KEY_U,
        "KEY_I" => EV_KEY::KEY_I,
        "KEY_O" => EV_KEY::KEY_O,
        "KEY_P" => EV_KEY::KEY_P,
        "KEY_LEFTBRACE" => EV_KEY::KEY_LEFTBRACE,
        "KEY_RIGHTBRACE" => EV_KEY::KEY_RIGHTBRACE,
        "KEY_ENTER" => EV_KEY::KEY_ENTER,
        "KEY_LEFTCTRL" => EV_KEY::KEY_LEFTCTRL,
        "KEY_A" => EV_KEY::KEY_A,
        "KEY_S" => EV_KEY::KEY_S,
        "KEY_D" => EV_KEY::KEY_D,
        "KEY_F" => EV_KEY::KEY_F,
        "KEY_G" => EV_KEY::KEY_G,
        "KEY_H" => EV_KEY::KEY_H,
        "KEY_J" => EV_KEY::KEY_J,
        "KEY_K" => EV_KEY::KEY_K,
        "KEY_L" => EV_KEY::KEY_L,
        "KEY_SEMICOLON" => EV_KEY::KEY_SEMICOLON,
        "KEY_APOSTROPHE" => EV_KEY::KEY_APOSTROPHE,
        "KEY_GRAVE" => EV_KEY::KEY_GRAVE,
        "KEY_LEFTSHIFT" => EV_KEY::KEY_LEFTSHIFT,
        "KEY_BACKSLASH" => EV_KEY::KEY_BACKSLASH,
        "KEY_Z" => EV_KEY::KEY_Z,
        "KEY_X" => EV_KEY::KEY_X,
        "KEY_C" => EV_KEY::KEY_C,
        "KEY_V" => EV_KEY::KEY_V,
        "KEY_B" => EV_KEY::KEY_B,
        "KEY_N" => EV_KEY::KEY_N,
        "KEY_M" => EV_KEY::KEY_M,
        "KEY_COMMA" => EV_KEY::KEY_COMMA,
        "KEY_DOT" => EV_KEY::KEY_DOT,
        "KEY_SLASH" => EV_KEY::KEY_SLASH,
        "KEY_RIGHTSHIFT" => EV_KEY::KEY_RIGHTSHIFT,
        "KEY_KPASTERISK" => EV_KEY::KEY_KPASTERISK,
        "KEY_LEFTALT" => EV_KEY::KEY_LEFTALT,
        "KEY_SPACE" => EV_KEY::KEY_SPACE,
        "KEY_CAPSLOCK" => EV_KEY::KEY_CAPSLOCK,
        "KEY_F1" => EV_KEY::KEY_F1,
        "KEY_F2" => EV_KEY::KEY_F2,
        "KEY_F3" => EV_KEY::KEY_F3,
        "KEY_F4" => EV_KEY::KEY_F4,
        "KEY_F5" => EV_KEY::KEY_F5,
        "KEY_F6" => EV_KEY::KEY_F6,
        "KEY_F7" => EV_KEY::KEY_F7,
        "KEY_F8" => EV_KEY::KEY_F8,
        "KEY_F9" => EV_KEY::KEY_F9,
        "KEY_F10" => EV_KEY::KEY_F10,
        "KEY_NUMLOCK" => EV_KEY::KEY_NUMLOCK,
        "KEY_SCROLLLOCK" => EV_KEY::KEY_SCROLLLOCK,
        "KEY_KP7" => EV_KEY::KEY_KP7,
        "KEY_KP8" => EV_KEY::KEY_KP8,
        "KEY_KP9" => EV_KEY::KEY_KP9,
        "KEY_KPMINUS" => EV_KEY::KEY_KPMINUS,
        "KEY_KP4" => EV_KEY::KEY_KP4,
        "KEY_KP5" => EV_KEY::KEY_KP5,
        "KEY_KP6" => EV_KEY::KEY_KP6,
        "KEY_KPPLUS" => EV_KEY::KEY_KPPLUS,
        "KEY_KP1" => EV_KEY::KEY_KP1,
        "KEY_KP2" => EV_KEY::KEY_KP2,
        "KEY_KP3" => EV_KEY::KEY_KP3,
        "KEY_KP0" => EV_KEY::KEY_KP0,
        "KEY_KPDOT" => EV_KEY::KEY_KPDOT,
        "KEY_ZENKAKUHANKAKU" => EV_KEY::KEY_ZENKAKUHANKAKU,
        "KEY_102ND" => EV_KEY::KEY_102ND,
        "KEY_F11" => EV_KEY::KEY_F11,
        "KEY_F12" => EV_KEY::KEY_F12,
        "KEY_RO" => EV_KEY::KEY_RO,
        "KEY_KATAKANA" => EV_KEY::KEY_KATAKANA,
        "KEY_HIRAGANA" => EV_KEY::KEY_HIRAGANA,
        "KEY_HENKAN" => EV_KEY::KEY_HENKAN,
        "KEY_KATAKANAHIRAGANA" => EV_KEY::KEY_KATAKANAHIRAGANA,
        "KEY_MUHENKAN" => EV_KEY::KEY_MUHENKAN,
        "KEY_KPJPCOMMA" => EV_KEY::KEY_KPJPCOMMA,
        "KEY_KPENTER" => EV_KEY::KEY_KPENTER,
        "KEY_RIGHTCTRL" => EV_KEY::KEY_RIGHTCTRL,
        "KEY_KPSLASH" => EV_KEY::KEY_KPSLASH,
        "KEY_SYSRQ" => EV_KEY::KEY_SYSRQ,
        "KEY_RIGHTALT" => EV_KEY::KEY_RIGHTALT,
        "KEY_LINEFEED" => EV_KEY::KEY_LINEFEED,
        "KEY_HOME" => EV_KEY::KEY_HOME,
        "KEY_UP" => EV_KEY::KEY_UP,
        "KEY_PAGEUP" => EV_KEY::KEY_PAGEUP,
        "KEY_LEFT" => EV_KEY::KEY_LEFT,
        "KEY_RIGHT" => EV_KEY::KEY_RIGHT,
        "KEY_END" => EV_KEY::KEY_END,
        "KEY_DOWN" => EV_KEY::KEY_DOWN,
        "KEY_PAGEDOWN" => EV_KEY::KEY_PAGEDOWN,
        "KEY_INSERT" => EV_KEY::KEY_INSERT,
        "KEY_DELETE" => EV_KEY::KEY_DELETE,
        "KEY_MACRO" => EV_KEY::KEY_MACRO,
        "KEY_MUTE" => EV_KEY::KEY_MUTE,
        "KEY_VOLUMEDOWN" => EV_KEY::KEY_VOLUMEDOWN,
        "KEY_VOLUMEUP" => EV_KEY::KEY_VOLUMEUP,
        "KEY_POWER" => EV_KEY::KEY_POWER,
        "KEY_KPEQUAL" => EV_KEY::KEY_KPEQUAL,
        "KEY_KPPLUSMINUS" => EV_KEY::KEY_KPPLUSMINUS,
        "KEY_PAUSE" => EV_KEY::KEY_PAUSE,
        "KEY_SCALE" => EV_KEY::KEY_SCALE,
        "KEY_KPCOMMA" => EV_KEY::KEY_KPCOMMA,
        "KEY_HANGEUL" => EV_KEY::KEY_HANGEUL,
        "KEY_HANJA" => EV_KEY::KEY_HANJA,
        "KEY_YEN" => EV_KEY::KEY_YEN,
        "KEY_LEFTMETA" => EV_KEY::KEY_LEFTMETA,
        "KEY_RIGHTMETA" => EV_KEY::KEY_RIGHTMETA,
        "KEY_COMPOSE" => EV_KEY::KEY_COMPOSE,
        "KEY_STOP" => EV_KEY::KEY_STOP,
        "KEY_AGAIN" => EV_KEY::KEY_AGAIN,
        "KEY_PROPS" => EV_KEY::KEY_PROPS,
        "KEY_UNDO" => EV_KEY::KEY_UNDO,
        "KEY_FRONT" => EV_KEY::KEY_FRONT,
        "KEY_COPY" => EV_KEY::KEY_COPY,
        "KEY_OPEN" => EV_KEY::KEY_OPEN,
        "KEY_PASTE" => EV_KEY::KEY_PASTE,
        "KEY_FIND" => EV_KEY::KEY_FIND,
        "KEY_CUT" => EV_KEY::KEY_CUT,
        "KEY_HELP" => EV_KEY::KEY_HELP,
        "KEY_MENU" => EV_KEY::KEY_MENU,
        "KEY_CALC" => EV_KEY::KEY_CALC,
        "KEY_SETUP" => EV_KEY::KEY_SETUP,
        "KEY_SLEEP" => EV_KEY::KEY_SLEEP,
        "KEY_WAKEUP" => EV_KEY::KEY_WAKEUP,
        "KEY_FILE" => EV_KEY::KEY_FILE,
        "KEY_SENDFILE" => EV_KEY::KEY_SENDFILE,
        "KEY_DELETEFILE" => EV_KEY::KEY_DELETEFILE,
        "KEY_XFER" => EV_KEY::KEY_XFER,
        "KEY_PROG1" => EV_KEY::KEY_PROG1,
        "KEY_PROG2" => EV_KEY::KEY_PROG2,
        "KEY_WWW" => EV_KEY::KEY_WWW,
        "KEY_MSDOS" => EV_KEY::KEY_MSDOS,
        "KEY_COFFEE" => EV_KEY::KEY_COFFEE,
        "KEY_ROTATE_DISPLAY" => EV_KEY::KEY_ROTATE_DISPLAY,
        "KEY_CYCLEWINDOWS" => EV_KEY::KEY_CYCLEWINDOWS,
        "KEY_MAIL" => EV_KEY::KEY_MAIL,
        "KEY_BOOKMARKS" => EV_KEY::KEY_BOOKMARKS,
        "KEY_COMPUTER" => EV_KEY::KEY_COMPUTER,
        "KEY_BACK" => EV_KEY::KEY_BACK,
        "KEY_FORWARD" => EV_KEY::KEY_FORWARD,
        "KEY_CLOSECD" => EV_KEY::KEY_CLOSECD,
        "KEY_EJECTCD" => EV_KEY::KEY_EJECTCD,
        "KEY_EJECTCLOSECD" => EV_KEY::KEY_EJECTCLOSECD,
        "KEY_NEXTSONG" => EV_KEY::KEY_NEXTSONG,
        "KEY_PLAYPAUSE" => EV_KEY::KEY_PLAYPAUSE,
        "KEY_PREVIOUSSONG" => EV_KEY::KEY_PREVIOUSSONG,
        "KEY_STOPCD" => EV_KEY::KEY_STOPCD,
        "KEY_RECORD" => EV_KEY::KEY_RECORD,
        "KEY_REWIND" => EV_KEY::KEY_REWIND,
        "KEY_PHONE" => EV_KEY::KEY_PHONE,
        "KEY_ISO" => EV_KEY::KEY_ISO,
        "KEY_CONFIG" => EV_KEY::KEY_CONFIG,
        "KEY_HOMEPAGE" => EV_KEY::KEY_HOMEPAGE,
        "KEY_REFRESH" => EV_KEY::KEY_REFRESH,
        "KEY_EXIT" => EV_KEY::KEY_EXIT,
        "KEY_MOVE" => EV_KEY::KEY_MOVE,
        "KEY_EDIT" => EV_KEY::KEY_EDIT,
        "KEY_SCROLLUP" => EV_KEY::KEY_SCROLLUP,
        "KEY_SCROLLDOWN" => EV_KEY::KEY_SCROLLDOWN,
        "KEY_KPLEFTPAREN" => EV_KEY::KEY_KPLEFTPAREN,
        "KEY_KPRIGHTPAREN" => EV_KEY::KEY_KPRIGHTPAREN,
        "KEY_NEW" => EV_KEY::KEY_NEW,
        "KEY_REDO" => EV_KEY::KEY_REDO,
        "KEY_F13" => EV_KEY::KEY_F13,
        "KEY_F14" => EV_KEY::KEY_F14,
        "KEY_F15" => EV_KEY::KEY_F15,
        "KEY_F16" => EV_KEY::KEY_F16,
        "KEY_F17" => EV_KEY::KEY_F17,
        "KEY_F18" => EV_KEY::KEY_F18,
        "KEY_F19" => EV_KEY::KEY_F19,
        "KEY_F20" => EV_KEY::KEY_F20,
        "KEY_F21" => EV_KEY::KEY_F21,
        "KEY_F22" => EV_KEY::KEY_F22,
        "KEY_F23" => EV_KEY::KEY_F23,
        "KEY_F24" => EV_KEY::KEY_F24,
        "KEY_PLAYCD" => EV_KEY::KEY_PLAYCD,
        "KEY_PAUSECD" => EV_KEY::KEY_PAUSECD,
        "KEY_PROG3" => EV_KEY::KEY_PROG3,
        "KEY_PROG4" => EV_KEY::KEY_PROG4,
        "KEY_SUSPEND" => EV_KEY::KEY_SUSPEND,
        "KEY_CLOSE" => EV_KEY::KEY_CLOSE,
        "KEY_PLAY" => EV_KEY::KEY_PLAY,
        "KEY_FASTFORWARD" => EV_KEY::KEY_FASTFORWARD,
        "KEY_BASSBOOST" => EV_KEY::KEY_BASSBOOST,
        "KEY_PRINT" => EV_KEY::KEY_PRINT,
        "KEY_HP" => EV_KEY::KEY_HP,
        "KEY_CAMERA" => EV_KEY::KEY_CAMERA,
        "KEY_SOUND" => EV_KEY::KEY_SOUND,
        "KEY_QUESTION" => EV_KEY::KEY_QUESTION,
        "KEY_EMAIL" => EV_KEY::KEY_EMAIL,
        "KEY_CHAT" => EV_KEY::KEY_CHAT,
        "KEY_SEARCH" => EV_KEY::KEY_SEARCH,
        "KEY_CONNECT" => EV_KEY::KEY_CONNECT,
        "KEY_FINANCE" => EV_KEY::KEY_FINANCE,
        "KEY_SPORT" => EV_KEY::KEY_SPORT,
        "KEY_SHOP" => EV_KEY::KEY_SHOP,
        "KEY_ALTERASE" => EV_KEY::KEY_ALTERASE,
        "KEY_CANCEL" => EV_KEY::KEY_CANCEL,
        "KEY_BRIGHTNESSDOWN" => EV_KEY::KEY_BRIGHTNESSDOWN,
        "KEY_BRIGHTNESSUP" => EV_KEY::KEY_BRIGHTNESSUP,
        "KEY_MEDIA" => EV_KEY::KEY_MEDIA,
        "KEY_SWITCHVIDEOMODE" => EV_KEY::KEY_SWITCHVIDEOMODE,
        "KEY_KBDILLUMTOGGLE" => EV_KEY::KEY_KBDILLUMTOGGLE,
        "KEY_KBDILLUMDOWN" => EV_KEY::KEY_KBDILLUMDOWN,
        "KEY_KBDILLUMUP" => EV_KEY::KEY_KBDILLUMUP,
        "KEY_SEND" => EV_KEY::KEY_SEND,
        "KEY_REPLY" => EV_KEY::KEY_REPLY,
        "KEY_FORWARDMAIL" => EV_KEY::KEY_FORWARDMAIL,
        "KEY_SAVE" => EV_KEY::KEY_SAVE,
        "KEY_DOCUMENTS" => EV_KEY::KEY_DOCUMENTS,
        "KEY_BATTERY" => EV_KEY::KEY_BATTERY,
        "KEY_BLUETOOTH" => EV_KEY::KEY_BLUETOOTH,
        "KEY_WLAN" => EV_KEY::KEY_WLAN,
        "KEY_UWB" => EV_KEY::KEY_UWB,
        "KEY_UNKNOWN" => EV_KEY::KEY_UNKNOWN,
        "KEY_VIDEO_NEXT" => EV_KEY::KEY_VIDEO_NEXT,
        "KEY_VIDEO_PREV" => EV_KEY::KEY_VIDEO_PREV,
        "KEY_BRIGHTNESS_CYCLE" => EV_KEY::KEY_BRIGHTNESS_CYCLE,
        "KEY_BRIGHTNESS_AUTO" => EV_KEY::KEY_BRIGHTNESS_AUTO,
        "KEY_DISPLAY_OFF" => EV_KEY::KEY_DISPLAY_OFF,
        "KEY_WWAN" => EV_KEY::KEY_WWAN,
        "KEY_RFKILL" => EV_KEY::KEY_RFKILL,
        "KEY_MICMUTE" => EV_KEY::KEY_MICMUTE,
        "KEY_OK" => EV_KEY::KEY_OK,
        "KEY_SELECT" => EV_KEY::KEY_SELECT,
        "KEY_GOTO" => EV_KEY::KEY_GOTO,
        "KEY_CLEAR" => EV_KEY::KEY_CLEAR,
        "KEY_POWER2" => EV_KEY::KEY_POWER2,
        "KEY_OPTION" => EV_KEY::KEY_OPTION,
        "KEY_INFO" => EV_KEY::KEY_INFO,
        "KEY_TIME" => EV_KEY::KEY_TIME,
        "KEY_VENDOR" => EV_KEY::KEY_VENDOR,
        "KEY_ARCHIVE" => EV_KEY::KEY_ARCHIVE,
        "KEY_PROGRAM" => EV_KEY::KEY_PROGRAM,
        "KEY_CHANNEL" => EV_KEY::KEY_CHANNEL,
        "KEY_FAVORITES" => EV_KEY::KEY_FAVORITES,
        "KEY_EPG" => EV_KEY::KEY_EPG,
        "KEY_PVR" => EV_KEY::KEY_PVR,
        "KEY_MHP" => EV_KEY::KEY_MHP,
        "KEY_LANGUAGE" => EV_KEY::KEY_LANGUAGE,
        "KEY_TITLE" => EV_KEY::KEY_TITLE,
        "KEY_SUBTITLE" => EV_KEY::KEY_SUBTITLE,
        "KEY_ANGLE" => EV_KEY::KEY_ANGLE,
        "KEY_FULL_SCREEN" => EV_KEY::KEY_FULL_SCREEN,
        "KEY_MODE" => EV_KEY::KEY_MODE,
        "KEY_KEYBOARD" => EV_KEY::KEY_KEYBOARD,
        "KEY_ASPECT_RATIO" => EV_KEY::KEY_ASPECT_RATIO,
        "KEY_PC" => EV_KEY::KEY_PC,
        "KEY_TV" => EV_KEY::KEY_TV,
        "KEY_TV2" => EV_KEY::KEY_TV2,
        "KEY_VCR" => EV_KEY::KEY_VCR,
        "KEY_VCR2" => EV_KEY::KEY_VCR2,
        "KEY_SAT" => EV_KEY::KEY_SAT,
        "KEY_SAT2" => EV_KEY::KEY_SAT2,
        "KEY_CD" => EV_KEY::KEY_CD,
        "KEY_TAPE" => EV_KEY::KEY_TAPE,
        "KEY_RADIO" => EV_KEY::KEY_RADIO,
        "KEY_TUNER" => EV_KEY::KEY_TUNER,
        "KEY_PLAYER" => EV_KEY::KEY_PLAYER,
        "KEY_TEXT" => EV_KEY::KEY_TEXT,
        "KEY_DVD" => EV_KEY::KEY_DVD,
        "KEY_AUX" => EV_KEY::KEY_AUX,
        "KEY_MP3" => EV_KEY::KEY_MP3,
        "KEY_AUDIO" => EV_KEY::KEY_AUDIO,
        "KEY_VIDEO" => EV_KEY::KEY_VIDEO,
        "KEY_DIRECTORY" => EV_KEY::KEY_DIRECTORY,
        "KEY_LIST" => EV_KEY::KEY_LIST,
        "KEY_MEMO" => EV_KEY::KEY_MEMO,
        "KEY_CALENDAR" => EV_KEY::KEY_CALENDAR,
        "KEY_RED" => EV_KEY::KEY_RED,
        "KEY_GREEN" => EV_KEY::KEY_GREEN,
        "KEY_YELLOW" => EV_KEY::KEY_YELLOW,
        "KEY_BLUE" => EV_KEY::KEY_BLUE,
        "KEY_CHANNELUP" => EV_KEY::KEY_CHANNELUP,
        "KEY_CHANNELDOWN" => EV_KEY::KEY_CHANNELDOWN,
        "KEY_FIRST" => EV_KEY::KEY_FIRST,
        "KEY_LAST" => EV_KEY::KEY_LAST,
        "KEY_AB" => EV_KEY::KEY_AB,
        "KEY_NEXT" => EV_KEY::KEY_NEXT,
        "KEY_RESTART" => EV_KEY::KEY_RESTART,
        "KEY_SLOW" => EV_KEY::KEY_SLOW,
        "KEY_SHUFFLE" => EV_KEY::KEY_SHUFFLE,
        "KEY_BREAK" => EV_KEY::KEY_BREAK,
        "KEY_PREVIOUS" => EV_KEY::KEY_PREVIOUS,
        "KEY_DIGITS" => EV_KEY::KEY_DIGITS,
        "KEY_TEEN" => EV_KEY::KEY_TEEN,
        "KEY_TWEN" => EV_KEY::KEY_TWEN,
        "KEY_VIDEOPHONE" => EV_KEY::KEY_VIDEOPHONE,
        "KEY_GAMES" => EV_KEY::KEY_GAMES,
        "KEY_ZOOMIN" => EV_KEY::KEY_ZOOMIN,
        "KEY_ZOOMOUT" => EV_KEY::KEY_ZOOMOUT,
        "KEY_ZOOMRESET" => EV_KEY::KEY_ZOOMRESET,
        "KEY_WORDPROCESSOR" => EV_KEY::KEY_WORDPROCESSOR,
        "KEY_EDITOR" => EV_KEY::KEY_EDITOR,
        "KEY_SPREADSHEET" => EV_KEY::KEY_SPREADSHEET,
        "KEY_GRAPHICSEDITOR" => EV_KEY::KEY_GRAPHICSEDITOR,
        "KEY_PRESENTATION" => EV_KEY::KEY_PRESENTATION,
        "KEY_DATABASE" => EV_KEY::KEY_DATABASE,
        "KEY_NEWS" => EV_KEY::KEY_NEWS,
        "KEY_VOICEMAIL" => EV_KEY::KEY_VOICEMAIL,
        "KEY_ADDRESSBOOK" => EV_KEY::KEY_ADDRESSBOOK,
        "KEY_MESSENGER" => EV_KEY::KEY_MESSENGER,
        "KEY_DISPLAYTOGGLE" => EV_KEY::KEY_DISPLAYTOGGLE,
        "KEY_SPELLCHECK" => EV_KEY::KEY_SPELLCHECK,
        "KEY_LOGOFF" => EV_KEY::KEY_LOGOFF,
        "KEY_DOLLAR" => EV_KEY::KEY_DOLLAR,
        "KEY_EURO" => EV_KEY::KEY_EURO,
        "KEY_FRAMEBACK" => EV_KEY::KEY_FRAMEBACK,
        "KEY_FRAMEFORWARD" => EV_KEY::KEY_FRAMEFORWARD,
        "KEY_CONTEXT_MENU" => EV_KEY::KEY_CONTEXT_MENU,
        "KEY_MEDIA_REPEAT" => EV_KEY::KEY_MEDIA_REPEAT,
        "KEY_10CHANNELSUP" => EV_KEY::KEY_10CHANNELSUP,
        "KEY_10CHANNELSDOWN" => EV_KEY::KEY_10CHANNELSDOWN,
        "KEY_IMAGES" => EV_KEY::KEY_IMAGES,
        "KEY_DEL_EOL" => EV_KEY::KEY_DEL_EOL,
        "KEY_DEL_EOS" => EV_KEY::KEY_DEL_EOS,
        "KEY_INS_LINE" => EV_KEY::KEY_INS_LINE,
        "KEY_DEL_LINE" => EV_KEY::KEY_DEL_LINE,
        "KEY_FN" => EV_KEY::KEY_FN,
        "KEY_FN_ESC" => EV_KEY::KEY_FN_ESC,
        "KEY_FN_F1" => EV_KEY::KEY_FN_F1,
        "KEY_FN_F2" => EV_KEY::KEY_FN_F2,
        "KEY_FN_F3" => EV_KEY::KEY_FN_F3,
        "KEY_FN_F4" => EV_KEY::KEY_FN_F4,
        "KEY_FN_F5" => EV_KEY::KEY_FN_F5,
        "KEY_FN_F6" => EV_KEY::KEY_FN_F6,
        "KEY_FN_F7" => EV_KEY::KEY_FN_F7,
        "KEY_FN_F8" => EV_KEY::KEY_FN_F8,
        "KEY_FN_F9" => EV_KEY::KEY_FN_F9,
        "KEY_FN_F10" => EV_KEY::KEY_FN_F10,
        "KEY_FN_F11" => EV_KEY::KEY_FN_F11,
        "KEY_FN_F12" => EV_KEY::KEY_FN_F12,
        "KEY_FN_1" => EV_KEY::KEY_FN_1,
        "KEY_FN_2" => EV_KEY::KEY_FN_2,
        "KEY_FN_D" => EV_KEY::KEY_FN_D,
        "KEY_FN_E" => EV_KEY::KEY_FN_E,
        "KEY_FN_F" => EV_KEY::KEY_FN_F,
        "KEY_FN_S" => EV_KEY::KEY_FN_S,
        "KEY_FN_B" => EV_KEY::KEY_FN_B,
        "KEY_BRL_DOT1" => EV_KEY::KEY_BRL_DOT1,
        "KEY_BRL_DOT2" => EV_KEY::KEY_BRL_DOT2,
        "KEY_BRL_DOT3" => EV_KEY::KEY_BRL_DOT3,
        "KEY_BRL_DOT4" => EV_KEY::KEY_BRL_DOT4,
        "KEY_BRL_DOT5" => EV_KEY::KEY_BRL_DOT5,
        "KEY_BRL_DOT6" => EV_KEY::KEY_BRL_DOT6,
        "KEY_BRL_DOT7" => EV_KEY::KEY_BRL_DOT7,
        "KEY_BRL_DOT8" => EV_KEY::KEY_BRL_DOT8,
        "KEY_BRL_DOT9" => EV_KEY::KEY_BRL_DOT9,
        "KEY_BRL_DOT10" => EV_KEY::KEY_BRL_DOT10,
        "KEY_NUMERIC_0" => EV_KEY::KEY_NUMERIC_0,
        "KEY_NUMERIC_1" => EV_KEY::KEY_NUMERIC_1,
        "KEY_NUMERIC_2" => EV_KEY::KEY_NUMERIC_2,
        "KEY_NUMERIC_3" => EV_KEY::KEY_NUMERIC_3,
        "KEY_NUMERIC_4" => EV_KEY::KEY_NUMERIC_4,
        "KEY_NUMERIC_5" => EV_KEY::KEY_NUMERIC_5,
        "KEY_NUMERIC_6" => EV_KEY::KEY_NUMERIC_6,
        "KEY_NUMERIC_7" => EV_KEY::KEY_NUMERIC_7,
        "KEY_NUMERIC_8" => EV_KEY::KEY_NUMERIC_8,
        "KEY_NUMERIC_9" => EV_KEY::KEY_NUMERIC_9,
        "KEY_NUMERIC_STAR" => EV_KEY::KEY_NUMERIC_STAR,
        "KEY_NUMERIC_POUND" => EV_KEY::KEY_NUMERIC_POUND,
        "KEY_NUMERIC_A" => EV_KEY::KEY_NUMERIC_A,
        "KEY_NUMERIC_B" => EV_KEY::KEY_NUMERIC_B,
        "KEY_NUMERIC_C" => EV_KEY::KEY_NUMERIC_C,
        "KEY_NUMERIC_D" => EV_KEY::KEY_NUMERIC_D,
        "KEY_CAMERA_FOCUS" => EV_KEY::KEY_CAMERA_FOCUS,
        "KEY_WPS_BUTTON" => EV_KEY::KEY_WPS_BUTTON,
        "KEY_TOUCHPAD_TOGGLE" => EV_KEY::KEY_TOUCHPAD_TOGGLE,
        "KEY_TOUCHPAD_ON" => EV_KEY::KEY_TOUCHPAD_ON,
        "KEY_TOUCHPAD_OFF" => EV_KEY::KEY_TOUCHPAD_OFF,
        "KEY_CAMERA_ZOOMIN" => EV_KEY::KEY_CAMERA_ZOOMIN,
        "KEY_CAMERA_ZOOMOUT" => EV_KEY::KEY_CAMERA_ZOOMOUT,
        "KEY_CAMERA_UP" => EV_KEY::KEY_CAMERA_UP,
        "KEY_CAMERA_DOWN" => EV_KEY::KEY_CAMERA_DOWN,
        "KEY_CAMERA_LEFT" => EV_KEY::KEY_CAMERA_LEFT,
        "KEY_CAMERA_RIGHT" => EV_KEY::KEY_CAMERA_RIGHT,
        "KEY_ATTENDANT_ON" => EV_KEY::KEY_ATTENDANT_ON,
        "KEY_ATTENDANT_OFF" => EV_KEY::KEY_ATTENDANT_OFF,
        "KEY_ATTENDANT_TOGGLE" => EV_KEY::KEY_ATTENDANT_TOGGLE,
        "KEY_LIGHTS_TOGGLE" => EV_KEY::KEY_LIGHTS_TOGGLE,
        "KEY_ALS_TOGGLE" => EV_KEY::KEY_ALS_TOGGLE,
        "KEY_ROTATE_LOCK_TOGGLE" => EV_KEY::KEY_ROTATE_LOCK_TOGGLE,
        "KEY_BUTTONCONFIG" => EV_KEY::KEY_BUTTONCONFIG,
        "KEY_TASKMANAGER" => EV_KEY::KEY_TASKMANAGER,
        "KEY_JOURNAL" => EV_KEY::KEY_JOURNAL,
        "KEY_CONTROLPANEL" => EV_KEY::KEY_CONTROLPANEL,
        "KEY_APPSELECT" => EV_KEY::KEY_APPSELECT,
        "KEY_SCREENSAVER" => EV_KEY::KEY_SCREENSAVER,
        "KEY_VOICECOMMAND" => EV_KEY::KEY_VOICECOMMAND,
        "KEY_ASSISTANT" => EV_KEY::KEY_ASSISTANT,
        "KEY_KBD_LAYOUT_NEXT" => EV_KEY::KEY_KBD_LAYOUT_NEXT,
        "KEY_BRIGHTNESS_MIN" => EV_KEY::KEY_BRIGHTNESS_MIN,
        "KEY_BRIGHTNESS_MAX" => EV_KEY::KEY_BRIGHTNESS_MAX,
        "KEY_KBDINPUTASSIST_PREV" => EV_KEY::KEY_KBDINPUTASSIST_PREV,
        "KEY_KBDINPUTASSIST_NEXT" => EV_KEY::KEY_KBDINPUTASSIST_NEXT,
        "KEY_KBDINPUTASSIST_PREVGROUP" => EV_KEY::KEY_KBDINPUTASSIST_PREVGROUP,
        "KEY_KBDINPUTASSIST_NEXTGROUP" => EV_KEY::KEY_KBDINPUTASSIST_NEXTGROUP,
        "KEY_KBDINPUTASSIST_ACCEPT" => EV_KEY::KEY_KBDINPUTASSIST_ACCEPT,
        "KEY_KBDINPUTASSIST_CANCEL" => EV_KEY::KEY_KBDINPUTASSIST_CANCEL,
        "KEY_RIGHT_UP" => EV_KEY::KEY_RIGHT_UP,
        "KEY_RIGHT_DOWN" => EV_KEY::KEY_RIGHT_DOWN,
        "KEY_LEFT_UP" => EV_KEY::KEY_LEFT_UP,
        "KEY_LEFT_DOWN" => EV_KEY::KEY_LEFT_DOWN,
        "KEY_ROOT_MENU" => EV_KEY::KEY_ROOT_MENU,
        "KEY_MEDIA_TOP_MENU" => EV_KEY::KEY_MEDIA_TOP_MENU,
        "KEY_NUMERIC_11" => EV_KEY::KEY_NUMERIC_11,
        "KEY_NUMERIC_12" => EV_KEY::KEY_NUMERIC_12,
        "KEY_AUDIO_DESC" => EV_KEY::KEY_AUDIO_DESC,
        "KEY_3D_MODE" => EV_KEY::KEY_3D_MODE,
        "KEY_NEXT_FAVORITE" => EV_KEY::KEY_NEXT_FAVORITE,
        "KEY_STOP_RECORD" => EV_KEY::KEY_STOP_RECORD,
        "KEY_PAUSE_RECORD" => EV_KEY::KEY_PAUSE_RECORD,
        "KEY_VOD" => EV_KEY::KEY_VOD,
        "KEY_UNMUTE" => EV_KEY::KEY_UNMUTE,
        "KEY_FASTREVERSE" => EV_KEY::KEY_FASTREVERSE,
        "KEY_SLOWREVERSE" => EV_KEY::KEY_SLOWREVERSE,
        "KEY_DATA" => EV_KEY::KEY_DATA,
        "KEY_ONSCREEN_KEYBOARD" => EV_KEY::KEY_ONSCREEN_KEYBOARD,
        "KEY_MAX" => EV_KEY::KEY_MAX,
    };

    map.get(&event).cloned()
}

pub fn int_to_evdev_key_event(code: u32) -> Option<EV_KEY> {
    int_to_ev_key(code)
}

pub fn evdev_key_event_to_int(event: EventCode) -> u32 {
    match event {
        EventCode::EV_KEY(code) => code as u32,

        EventCode::EV_SYN(code) => code as u32,

        EventCode::EV_REL(code) => code as u32,

        EventCode::EV_ABS(code) => code as u32,

        EventCode::EV_MSC(code) => code as u32,

        EventCode::EV_SW(code) => code as u32,

        EventCode::EV_LED(code) => code as u32,

        EventCode::EV_SND(code) => code as u32,

        EventCode::EV_REP(code) => code as u32,

        EventCode::EV_FF(code) => code as u32,

        EventCode::EV_PWR => 0,

        EventCode::EV_FF_STATUS(code) => code as u32,

        EventCode::EV_UNK {
            event_type: _,
            event_code,
        } => event_code,

        EventCode::EV_MAX => 0,
    }
}

pub fn symbol_to_key_index(symbol: &str, (usb_vid, usb_pid): (u16, u16)) -> Option<usize> {
    if let Some(event) = evdev_event_code_from_string(&symbol.to_uppercase()) {
        hwdevices::ev_key_to_index(&event, (usb_vid, usb_pid)).map(|e| e + 1)
    } else {
        symbol.parse::<usize>().ok()
    }
}

pub fn key_index_to_symbol(index: usize, (usb_vid, usb_pid): (u16, u16)) -> Option<String> {
    let ev_key = hwdevices::index_to_ev_key(index, (usb_vid, usb_pid))?;

    Some(evdev_event_code_to_string(ev_key as u32))
}
