// This code was autogenerated with `dbus-codegen-rust --system-bus --prop-newtype --destination org.eruption --path /org/eruption/profile`, see https://github.com/diwic/dbus-rs
use dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgEruptionProfile {
    fn enum_profiles(&self) -> Result<Vec<(String, String)>, dbus::Error>;
    fn set_parameter(
        &self,
        profile_file: &str,
        script_file: &str,
        param_name: &str,
        value: &str,
    ) -> Result<bool, dbus::Error>;
    fn switch_profile(&self, filename: &str) -> Result<bool, dbus::Error>;
    fn active_profile(&self) -> Result<String, dbus::Error>;
}

#[derive(Debug)]
pub struct OrgEruptionProfileActiveProfileChanged {
    pub profile_name: String,
}

impl arg::AppendAll for OrgEruptionProfileActiveProfileChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.profile_name, i);
    }
}

impl arg::ReadAll for OrgEruptionProfileActiveProfileChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgEruptionProfileActiveProfileChanged {
            profile_name: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgEruptionProfileActiveProfileChanged {
    const NAME: &'static str = "ActiveProfileChanged";
    const INTERFACE: &'static str = "org.eruption.Profile";
}

#[derive(Debug)]
pub struct OrgEruptionProfileProfilesChanged {}

impl arg::AppendAll for OrgEruptionProfileProfilesChanged {
    fn append(&self, _: &mut arg::IterAppend) {}
}

impl arg::ReadAll for OrgEruptionProfileProfilesChanged {
    fn read(_: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgEruptionProfileProfilesChanged {})
    }
}

impl dbus::message::SignalArgs for OrgEruptionProfileProfilesChanged {
    const NAME: &'static str = "ProfilesChanged";
    const INTERFACE: &'static str = "org.eruption.Profile";
}

pub const ORG_ERUPTION_PROFILE_NAME: &str = "org.eruption.Profile";

#[derive(Copy, Clone, Debug)]
pub struct OrgEruptionProfileProperties<'a>(pub &'a arg::PropMap);

impl<'a> OrgEruptionProfileProperties<'a> {
    pub fn from_interfaces(
        interfaces: &'a ::std::collections::HashMap<String, arg::PropMap>,
    ) -> Option<Self> {
        interfaces.get("org.eruption.Profile").map(Self)
    }

    pub fn active_profile(&self) -> Option<&String> {
        arg::prop_cast(self.0, "ActiveProfile")
    }
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> OrgEruptionProfile
    for blocking::Proxy<'a, C>
{
    fn enum_profiles(&self) -> Result<Vec<(String, String)>, dbus::Error> {
        self.method_call("org.eruption.Profile", "EnumProfiles", ())
            .and_then(|r: (Vec<(String, String)>,)| Ok(r.0))
    }

    fn set_parameter(
        &self,
        profile_file: &str,
        script_file: &str,
        param_name: &str,
        value: &str,
    ) -> Result<bool, dbus::Error> {
        self.method_call(
            "org.eruption.Profile",
            "SetParameter",
            (profile_file, script_file, param_name, value),
        )
        .and_then(|r: (bool,)| Ok(r.0))
    }

    fn switch_profile(&self, filename: &str) -> Result<bool, dbus::Error> {
        self.method_call("org.eruption.Profile", "SwitchProfile", (filename,))
            .and_then(|r: (bool,)| Ok(r.0))
    }

    fn active_profile(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            &self,
            "org.eruption.Profile",
            "ActiveProfile",
        )
    }
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> Result<String, dbus::Error>;
}

pub const ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_NAME: &str = "org.freedesktop.DBus.Introspectable";

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>>
    OrgFreedesktopDBusIntrospectable for blocking::Proxy<'a, C>
{
    fn introspect(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String,)| Ok(r.0))
    }
}

pub trait OrgFreedesktopDBusProperties {
    fn get(
        &self,
        interface_name: &str,
        property_name: &str,
    ) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error>;
    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error>;
    fn set(
        &self,
        interface_name: &str,
        property_name: &str,
        value: arg::Variant<Box<dyn arg::RefArg>>,
    ) -> Result<(), dbus::Error>;
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

pub const ORG_FREEDESKTOP_DBUS_PROPERTIES_NAME: &str = "org.freedesktop.DBus.Properties";

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> OrgFreedesktopDBusProperties
    for blocking::Proxy<'a, C>
{
    fn get(
        &self,
        interface_name: &str,
        property_name: &str,
    ) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "Get",
            (interface_name, property_name),
        )
        .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>,)| Ok(r.0))
    }

    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "GetAll",
            (interface_name,),
        )
        .and_then(|r: (arg::PropMap,)| Ok(r.0))
    }

    fn set(
        &self,
        interface_name: &str,
        property_name: &str,
        value: arg::Variant<Box<dyn arg::RefArg>>,
    ) -> Result<(), dbus::Error> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "Set",
            (interface_name, property_name, value),
        )
    }
}
