Document: eruption-roccat-vulcan-git
Title: Debian eruption-roccat-vulcan-git Manual
Author: <insert document author here>
Abstract: This manual describes what eruption-roccat-vulcan-git is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/eruption-roccat-vulcan-git/eruption-roccat-vulcan-git.sgml.gz

Format: postscript
Files: /usr/share/doc/eruption-roccat-vulcan-git/eruption-roccat-vulcan-git.ps.gz

Format: text
Files: /usr/share/doc/eruption-roccat-vulcan-git/eruption-roccat-vulcan-git.text.gz

Format: HTML
Index: /usr/share/doc/eruption-roccat-vulcan-git/html/index.html
Files: /usr/share/doc/eruption-roccat-vulcan-git/html/*.html
