#  SPDX-License-Identifier: GPL-3.0-or-later
#
#  This file is part of Eruption.
#
#  Eruption is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Eruption is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Eruption.  If not, see <http://www.gnu.org/licenses/>.
#
#  Copyright (c) 2019-2023, The Eruption Development Team

[alias]
xtask = "run --manifest-path ./xtask/Cargo.toml --"

[future-incompat-report]
frequency = "always"

# NOTE:
# To improve build-time performance and reduce turn-around cycle time
# we enable some nightly/unstable features of the compiler frontend, the
# code-generator, and switch to `mold`, a high-perfomance multi-threaded
# linker

# Enable the `cranelift` code generator backend, the multi-threaded
# compiler-frontend and use the `mold` linker
[unstable]
codegen-backend = true
# sanitizer = true

[build]
rustflags = [
  # "--cfg",
  # "-Zthreads=8",
  "-Clink-arg=-fuse-ld=mold",
  # "-Ctarget-cpu=native",
  "-Zshare-generics=y",
  "-Clink-arg=-Wl,--no-rosegment",
  # "-Zsanitizer=thread",
  # "-Zsanitizer=address",
  # "-Zsanitizer=leak",
]

[profile.dev]
codegen-backend = "cranelift"

[profile.dev-optimized]
codegen-backend = "llvm"

[profile.release]
codegen-backend = "llvm"
rustflags = [
  # "--cfg",
  # "-Zthreads=8",
  # "-Clink-arg=-fuse-ld=mold",
  # "-Ctarget-cpu=native",
  # "-Zshare-generics=y",
  # "-Clink-arg=-Wl,--no-rosegment",
  # "-Zsanitizer=thread",
  # "-Zsanitizer=address",
  # "-Zsanitizer=leak",
]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"

[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/lld"
