# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk-support.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sdk-support.proto\x12\x0bsdk_support\"T\n\x07Request\x12.\n\x0crequest_type\x18\x01 \x01(\x0e\x32\x18.sdk_support.RequestType\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\t\n\x07Payload\"V\n\x08Response\x12/\n\rresponse_type\x18\x01 \x01(\x0e\x32\x18.sdk_support.RequestType\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\t\n\x07Payload*G\n\x0bRequestType\x12\x08\n\x04NOOP\x10\x00\x12\n\n\x06STATUS\x10\x01\x12\x0e\n\nSET_CANVAS\x10\x02\x12\x12\n\x0eNOTIFY_HOTPLUG\x10\x03\x32@\n\nSdkSupport\x12\x32\n\x03Sdk\x12\x14.sdk_support.Request\x1a\x15.sdk_support.Responseb\x06proto3')

_REQUESTTYPE = DESCRIPTOR.enum_types_by_name['RequestType']
RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
NOOP = 0
STATUS = 1
SET_CANVAS = 2
NOTIFY_HOTPLUG = 3


_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'sdk_support_pb2'
  # @@protoc_insertion_point(class_scope:sdk_support.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'sdk_support_pb2'
  # @@protoc_insertion_point(class_scope:sdk_support.Response)
  })
_sym_db.RegisterMessage(Response)

_SDKSUPPORT = DESCRIPTOR.services_by_name['SdkSupport']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTTYPE._serialized_start=208
  _REQUESTTYPE._serialized_end=279
  _REQUEST._serialized_start=34
  _REQUEST._serialized_end=118
  _RESPONSE._serialized_start=120
  _RESPONSE._serialized_end=206
  _SDKSUPPORT._serialized_start=281
  _SDKSUPPORT._serialized_end=345
# @@protoc_insertion_point(module_scope)
