#  SPDX-License-Identifier: GPL-3.0-or-later
#
#  This file is part of Eruption.
#
#  Eruption is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Eruption is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Eruption.  If not, see <http://www.gnu.org/licenses/>.
#
#  Copyright (c) 2019-2023, The Eruption Development Team

on:
    push:
        branches:
            - unified-canvas

name: Build Installer for Microsoft Windows
jobs:
  windows_installer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Base System
        run: "sudo apt-get update -y -qq; sudo apt-get install --assume-yes nsis"
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install cross Build Tool
        run: 'cargo install cross'
      - name: Run make windows-installer
        run: 'make windows-installer'
      - name: Publish Installer Binary
        uses: softprops/action-gh-release@v1
        with:
            files: 'target/Eruption.exe'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
